
import { defineUserConfig } from '@vuepress/cli'
import { defaultTheme } from '@vuepress/theme-default'

import { viteBundler } from '@vuepress/bundler-vite'

import { backToTopPlugin } from '@vuepress/plugin-back-to-top'
import { mediumZoomPlugin } from '@vuepress/plugin-medium-zoom'
import { containerPlugin } from '@vuepress/plugin-container'
import { nprogressPlugin } from '@vuepress/plugin-nprogress'


export default defineUserConfig({
    base: '/',
    lang: 'zh-CN',
    title: 'AimuBot',
    description: 'AimuBot是一个多功能机器人。',

    head: [
        ['link', { rel: 'icon', href: '/images/head.jpg' }],
    ],

    host: '127.0.0.1',
    port: 8080,

    plugins: [
        backToTopPlugin(),
        nprogressPlugin(),
        mediumZoomPlugin({
            // options
        }),
        containerPlugin({
            type: 'slot',
            before: (info: string): string => "<div class=\"footer content__footer\"><p>",
            after: (): string => '</p></div>\n'
        }),
    ],

    bundler: viteBundler({
        viteOptions: {
            // @ts-expect-error: vite does not provide types for ssr options yet
            ssr: {
                //noExternal: ['wow.js'],
            },
        },
        vuePluginOptions: {},
    }),

    theme: defaultTheme({
        logo: '/images/head.jpg',

        tip: '提示',
        warning: '注意',
        danger: '警告',

        repo: 'https://github.com/InariAimu/AimuBot',

        editLink: false,
        editLinkText: '编辑此页',
        docsRepo: 'https://github.com/InariAimu/AimuBot.Docs',
        docsBranch: 'main',
        docsDir: 'docs',

        lastUpdated: true,
        lastUpdatedText: '最近更新',

        navbar: [
            { text: '主页', link: '/', },
            { text: '简介', link: '/intro/' },
            { text: '模块', link: '/modules/' },
        ],

        sidebar: {
            '/intro/': [
                {
                    text: '简介',
                    collapsible: true,
                    children: [
                        '/intro/',
                        '/intro/command',
                        '/intro/about',
                    ]
                }
            ],
            '/modules/': [
                {
                    text: '模块',
                    collapsible: true,
                    children: [
                        '/modules/',
                        // <auto-generated>
                        '/modules/Admin',
                        '/modules/AlterInst',
                        '/modules/Arcaea',
                        '/modules/Arknights',
                        '/modules/Biaoqingbao',
                        '/modules/BotMyAdmin',
                        '/modules/Entertainment',
                        '/modules/Help',
                        '/modules/Information',
                        '/modules/Misc',
                        '/modules/PythonInterop',
                        '/modules/Test',
                        '/modules/Vtuber',
                        '/modules/WolframAlpha',
                        // </auto-generated>
                    ]
                }
            ]
        },
        sidebarDepth: 1,
    }),
})
